# docker build -t pautlenrom -f DockerFile  . 
FROM ubuntu:18.04
RUN apt update
RUN apt install -y gcc
RUN apt install -y nasm
RUN apt install -y g++-multilib 
RUN apt install -y libc6-dev-i386
RUN apt install -y make
CMD ["bash"]
