FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y nasm
RUN apt-get install -y g++-multilib 
RUN apt-get install -y libc6-dev-i386
RUN apt-get install -y make
# Maybe valgrind
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y libc6-dbg:i386
RUN apt-get install -y valgrind
RUN apt-get install -y bison
RUN apt-get install -y flex
CMD ["bash"]
